#!/usr/bin/env perl
use 5.026;
use strict;
use warnings;
use Carp;

use Mojo::File qw(curfile path);
#  messy but otherwise the exe files don't work from arbitrary locations
use if !$ENV{PAR_0}, 'lib', eval {curfile->dirname->sibling('lib')->to_string};
use Mojolicious::Commands;

#  load up some dependencies when packing an executable
use if $ENV{BDV_PP_BUILDING}, 'BiodiverseR::PPDeps';

# Start command line interface for application
Mojolicious::Commands->start_app('BiodiverseR');

